version: '3.8'

services:
  frontend:
    image: location-app:v2.0
    networks:
      - location-network
    ports:
      - 8181:8181
  sql-db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: docker_db
      MYSQL_ROOT_PASSWORD: astafa@1234
    
    networks:
      - location-network
    volumes:
     - location-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: sql-db
      PMA_USER: root
      PMA_PASSWORD: astafa@1234
    ports:
      - 8080:80
    networks:
      - location-network

networks:
  location-network:
volumes:
  location-data: